### ISSUE TITLE
상단바 버튼 이상

### ISSUE THREAD

**Issue by goranmabi** [2DU/openNAMU-Skin-YouSoro#2]
위키 상단바의 버튼이 아래로 쳐지는 현상이 나타납니다. 지금은 css를 예전거로 돌려서 사라졌고요

**Comment by goranmabi** [comment]
아니네요.. 지금도 그러네요..

http://lovelyz.wiki/w/%EB%9F%AC%EB%B8%94%EB%A6%AC%EC%A6%88%EC%9C%84%ED%82%A4%3A%EB%8C%80%EB%AC%B8

**Comment by 2DU** [comment]
스킨 업데이트 해보셨나요

**Comment by goranmabi** [comment]
업데이트 했더니 저래요..

**Comment by 2DU** [comment]
스킨 업데이트요? 오픈나무 업뎃 말구

**Comment by goranmabi** [comment]
네.. 스킨 최신 버전 파일 받아서 씌웠어요

**Comment by 2DU** [comment]
![비교 1](http://namu.ml/image/7d43f816736f94bb09231b279878e47a3e51b51708a74c1f49d75d6b.png)
![비교 2](http://namu.ml/image/6f675e493bf77b8afb12be57b9ae47bb0c6e601c1a20f2a95991140e.png)

최신 버전 스킨에 비해서 폰트가 작은 걸 보니 적용이 제대로 안된 것 같은데...

**Comment by goranmabi** [comment]
흠.. 다시 해 볼까요?

**Comment by goranmabi** [comment]
다시 받아서 넣으니까 정상적으로 되네요. 왜 적용이 안되었는지.. ㅠㅠ

**Comment by 2DU** [comment]
된다니 다행이네요
